version: '3.1'

services:
##Db-контейнеры
  database:
    container_name: boss24-database
    image: mysql:5.7
    volumes:
      - "./.data/db:/var/lib/mysql"
    restart: always
    env_file: "./docker/db/config/.env"
    ports:
      - "3306:3306"

##Backend-контейнеры
  api-nginx:
    container_name: boss24-api-nginx
    build:
      context: ./docker/api
      dockerfile: nginx.docker
    volumes:
      - ./api:/var/www/api
      - ./docker/api/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker/api/nginx/logs:/var/log/nginx
    ports:
      - "8081:80"

  api-php-fpm:
    container_name: boss24-api-php-fpm
    build:
      context: ./docker/api
      dockerfile: php-fpm.docker
    volumes:
      - ./api:/var/www/api
    depends_on:
      - database
    working_dir: /var/www/api

##Frontend-контейнеры
  frontend-nginx:
    container_name: boss24-frontend-nginx
    build:
      context: ./docker/frontend
      dockerfile: nginx.docker
    volumes:
      - ./frontend:/var/www/frontend
      - ./docker/frontend/ngnix/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - api-php-fpm
    ports:
      - "8080:80"

  frontend-nodejs:
    container_name: boss24-frontend-node
    image: node:8.11.3-jessie
    volumes:
        - "./frontend:/var/www/frontend"
    working_dir: /var/www/frontend
    tty: true

## Вспомогательные сервисы
  phpmyadmin:
    container_name: boss24_pma
    image: phpmyadmin/phpmyadmin
    depends_on:
      - database
    env_file: "./docker/db/config/.env"
    ports:
      - "8011:80"